// Bed & Matresses Products Listings...
export const bedAndMatressesListings = [
  {
    id: "bed-and-mat1",
    img1: "/listings/bed&matress/listing-bed&mat1.avif",
    img2: "/listings/bed&matress/listing-h-bed&mat1.avif",
    prodName: "SONGESAND",
    prodInfo: 'Bedroom furniture, set of 4, brown, 160x200 cm (63x78 3/4 ")',
    price: 39960,
    prevPrice: 43960,
    rating: 5,
    ratings: 5,
    tags: [
      "furniture",
      "bed",
      "bedroom",
      "matress",
      "sleep",
      "bed-frame",
      "frame",
    ],
  },
  {
    id: "bed-and-mat2",
    img1: "/listings/bed&matress/listing-bed&mat2.avif",
    img2: "/listings/bed&matress/listing-h-bed&mat2.avif",
    prodName: "VESTMARKA",
    prodInfo: 'Sprung mattress, firm/light blue, 180x200 cm (70 7/8x78 3/4 ")',
    price: 11990,
    prevPrice: 18186,
    rating: 4,
    ratings: 102,
    tags: ["bed", "matresses", "bedroom", "matress", "sleep"],
  },
];
