// Decorations Products Listings...
export const decorationsListings = [
  {
    id: 'decoration1',
    img1: '/listings/decorations/listing-decoration1.avif',
    img2: '/listings/decorations/listing-h-decoration1.avif',
    prodName: 'SMYCKA',
    prodInfo: 'Artificial flower, in/outdoor/Dogwood pink, 56 cm (22 ")',
    price: 199,
    prevPrice: 279,
    rating: 4.5,
    ratings: 7,
    tags: [
      'deco',
      'decorations',
      'bed room',
      'decoration',
      'living room',
      'hall',
      'plants',
      'natural',
      'flowers',
    ],
  },
  {
    id: 'decoration2',
    img1: '/listings/decorations/listing-decoration2.avif',
    img2: '/listings/decorations/listing-h-decoration2.avif',
    prodName: 'KNOPPÄNG',
    prodInfo: 'Frame with poster, set of 8, flower market',
    price: 3490,
    prevPrice: 4886,
    rating: 0,
    ratings: 0,
    tags: [
      'deco',
      'decorations',
      'bed room',
      'decoration',
      'living room',
      'hall',
      'frames',
      'photo frame',
      'photo',
      'frame set',
    ],
  },
];
