// Lighting Products Listings...
export const lightingProductsListings = [
  {
    id: 'lighting1',
    img1: '/listings/lighting/listing-lighting1.avif',
    img2: '/listings/lighting/listing-h-lighting1.avif',
    prodName: 'BARLAST',
    prodInfo: 'Floor lamp, black/white, 150 cm (59 ")',
    price: 799,
    prevPrice: 1119,
    rating: 3,
    ratings: 40,
    tags: [
      'deco',
      'decorations',
      'bed room',
      'decoration',
      'living room',
      'hall',
      'lamp',
      'lamps',
      'lights',
      'lighting',
      'light lamps',
    ],
  },
  {
    id: 'lighting2',
    img1: '/listings/lighting/listing-lighting2.avif',
    img2: '/listings/lighting/listing-h-lighting2.avif',
    prodName: 'SNÖYRA',
    prodInfo:
      'LED lighting chain with 40 lights, indoor/battery-operated silver-colour',
    price: 699,
    prevPrice: 979,
    rating: 3.5,
    ratings: 3,
    tags: [
      'deco',
      'decorations',
      'bed room',
      'decoration',
      'living room',
      'hall',
      'lamp',
      'lamps',
      'lights',
      'lighting',
      'light lamps',
      'chain lights',
      'gold lights',
      'function lights',
    ],
  },
];
